### ISSUE TITLE
Improve Profile README format

### ISSUE THREAD

**Issue by yashksaini-coder** [MAVRICK-1/First-pr#2]
The basic profile readme format is too basic. If you want other contributors to come & add their profile. It would be beneficial to add several details to make them unique & stand out from the others. That way every new profile is unique & better in its own way.

This is my suggestion of a new profile template.

**Comment by MAVRICK-1** [comment]
@yashksaini-coder this was just a basic template there was anything to contribute this was just a guide for a workshop .

**Comment by yashksaini-coder** [comment]
Still I want to update & provide better format, if it is okay with you.

**Comment by MAVRICK-1** [comment]
Okay go ahead

**Comment by yashksaini-coder** [comment]
All changes done Do check the PR and merge those changes. @MAVRICK-1

**Comment by yashksaini-coder** [comment]
Thank you for merging the #3
